// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoV9Ei5zpE2pD0PDtqa0HQKKj6WQiRZf8',
    appId: '1:873899912878:web:eb6afb0739f2ed73b4873f',
    messagingSenderId: '873899912878',
    projectId: 'texspin-22abe',
    authDomain: 'texspin-22abe.firebaseapp.com',
    storageBucket: 'texspin-22abe.firebasestorage.app',
    measurementId: 'G-34SN3GSVPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8VIYz4J8cojxJBeA_HPnsr1DEh9RsK0U',
    appId: '1:873899912878:android:ed3740aaaa8bfaeab4873f',
    messagingSenderId: '873899912878',
    projectId: 'texspin-22abe',
    storageBucket: 'texspin-22abe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsb3EqAAnlh5VRMReZlmv6a3L4DCIsGOs',
    appId: '1:873899912878:ios:ef855334ff100530b4873f',
    messagingSenderId: '873899912878',
    projectId: 'texspin-22abe',
    storageBucket: 'texspin-22abe.firebasestorage.app',
    iosBundleId: 'com.iflorapnfopvtltd.texspin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsb3EqAAnlh5VRMReZlmv6a3L4DCIsGOs',
    appId: '1:873899912878:ios:99b2eb05451c93c1b4873f',
    messagingSenderId: '873899912878',
    projectId: 'texspin-22abe',
    storageBucket: 'texspin-22abe.firebasestorage.app',
    iosBundleId: 'com.example.convert2dart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoV9Ei5zpE2pD0PDtqa0HQKKj6WQiRZf8',
    appId: '1:873899912878:web:c4ee41c3d568a1c9b4873f',
    messagingSenderId: '873899912878',
    projectId: 'texspin-22abe',
    authDomain: 'texspin-22abe.firebaseapp.com',
    storageBucket: 'texspin-22abe.firebasestorage.app',
    measurementId: 'G-86L2100LYW',
  );
}
